# [build]
#   base = "react-welcome-app"
#   publish = "dist"
#   command = "npm run build"

# [dev]
#   command = "npm run dev"

[build]
  base = "react-welcome-app"
  command = "npm run build"
  publish = "dist"
